/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCareRouteImport } from './routes/_authenticated/care'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCheckInsRouteImport } from './routes/_authenticated/check-ins'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminCrisisRouteImport } from './routes/_authenticated/admin/crisis'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as ApiPublicEnvcheckRouteImport } from './routes/api/public/envcheck'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiV1AccountRouteImport } from './routes/api/v1/account'
import { Route as ApiV1CrisisResourcesRouteImport } from './routes/api/v1/crisis-resources'
import { Route as ApiV1EntitlementsRouteImport } from './routes/api/v1/entitlements'
import { Route as ApiV1ExercisesRouteImport } from './routes/api/v1/exercises'
import { Route as ApiV1ExportRouteImport } from './routes/api/v1/export'
import { Route as ApiV1HabitsRouteImport } from './routes/api/v1/habits'
import { Route as ApiV1MoodRouteImport } from './routes/api/v1/mood'
import { Route as ApiV1OnboardingRouteImport } from './routes/api/v1/onboarding'
import { Route as ApiV1PersonasRouteImport } from './routes/api/v1/personas'
import { Route as ApiV1PreferencesRouteImport } from './routes/api/v1/preferences'
import { Route as ApiV1ProfileRouteImport } from './routes/api/v1/profile'
import { Route as ApiV1ScreenersRouteImport } from './routes/api/v1/screeners'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId'
import { Route as ApiPublicHooksEvaluateNudgesRouteImport } from './routes/api/public/hooks/evaluate-nudges'
import { Route as ApiPublicHooksStripeWebhookRouteImport } from './routes/api/public/hooks/stripe-webhook'
import { Route as ApiV1BillingCheckoutRouteImport } from './routes/api/v1/billing/checkout'
import { Route as ApiV1BillingPortalRouteImport } from './routes/api/v1/billing/portal'
import { Route as ApiV1BillingVerifyReceiptRouteImport } from './routes/api/v1/billing/verify-receipt'
import { Route as ApiV1CallsSessionsRouteImport } from './routes/api/v1/calls/sessions'
import { Route as ApiV1ChatHistoryRouteImport } from './routes/api/v1/chat/history'
import { Route as ApiV1ChatMessagesRouteImport } from './routes/api/v1/chat/messages'
import { Route as ApiV1ChatThreadsRouteImport } from './routes/api/v1/chat/threads'
import { Route as ApiV1PushRegisterTokenRouteImport } from './routes/api/v1/push/register-token'
import { Route as ApiV1ChatMessagesStreamRouteImport } from './routes/api/v1/chat/messages/stream'
import { Route as ApiV1ScreenersTypeResponsesRouteImport } from './routes/api/v1/screeners/$type/responses'
import { Route as ApiV1AdminUsersUserIdCostRouteImport } from './routes/api/v1/admin/users/$userId/cost'
import { Route as ApiV1CallsSessionsIdEndRouteImport } from './routes/api/v1/calls/sessions/$id/end'
import { Route as ApiV1CallsSessionsIdTurnsRouteImport } from './routes/api/v1/calls/sessions/$id/turns'
import { Route as ApiV1ChatThreadsIdMessagesRouteImport } from './routes/api/v1/chat/threads/$id/messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareRoute = AuthenticatedCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInsRoute = AuthenticatedCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCrisisRoute =
  AuthenticatedAdminCrisisRouteImport.update({
    id: '/crisis',
    path: '/crisis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicEnvcheckRoute = ApiPublicEnvcheckRouteImport.update({
  id: '/api/public/envcheck',
  path: '/api/public/envcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountRoute = ApiV1AccountRouteImport.update({
  id: '/api/v1/account',
  path: '/api/v1/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CrisisResourcesRoute = ApiV1CrisisResourcesRouteImport.update({
  id: '/api/v1/crisis-resources',
  path: '/api/v1/crisis-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntitlementsRoute = ApiV1EntitlementsRouteImport.update({
  id: '/api/v1/entitlements',
  path: '/api/v1/entitlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExercisesRoute = ApiV1ExercisesRouteImport.update({
  id: '/api/v1/exercises',
  path: '/api/v1/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportRoute = ApiV1ExportRouteImport.update({
  id: '/api/v1/export',
  path: '/api/v1/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HabitsRoute = ApiV1HabitsRouteImport.update({
  id: '/api/v1/habits',
  path: '/api/v1/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MoodRoute = ApiV1MoodRouteImport.update({
  id: '/api/v1/mood',
  path: '/api/v1/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OnboardingRoute = ApiV1OnboardingRouteImport.update({
  id: '/api/v1/onboarding',
  path: '/api/v1/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PersonasRoute = ApiV1PersonasRouteImport.update({
  id: '/api/v1/personas',
  path: '/api/v1/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PreferencesRoute = ApiV1PreferencesRouteImport.update({
  id: '/api/v1/preferences',
  path: '/api/v1/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileRoute = ApiV1ProfileRouteImport.update({
  id: '/api/v1/profile',
  path: '/api/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScreenersRoute = ApiV1ScreenersRouteImport.update({
  id: '/api/v1/screeners',
  path: '/api/v1/screeners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksEvaluateNudgesRoute =
  ApiPublicHooksEvaluateNudgesRouteImport.update({
    id: '/api/public/hooks/evaluate-nudges',
    path: '/api/public/hooks/evaluate-nudges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeWebhookRoute =
  ApiPublicHooksStripeWebhookRouteImport.update({
    id: '/api/public/hooks/stripe-webhook',
    path: '/api/public/hooks/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1BillingCheckoutRoute = ApiV1BillingCheckoutRouteImport.update({
  id: '/api/v1/billing/checkout',
  path: '/api/v1/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingPortalRoute = ApiV1BillingPortalRouteImport.update({
  id: '/api/v1/billing/portal',
  path: '/api/v1/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingVerifyReceiptRoute =
  ApiV1BillingVerifyReceiptRouteImport.update({
    id: '/api/v1/billing/verify-receipt',
    path: '/api/v1/billing/verify-receipt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CallsSessionsRoute = ApiV1CallsSessionsRouteImport.update({
  id: '/api/v1/calls/sessions',
  path: '/api/v1/calls/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatHistoryRoute = ApiV1ChatHistoryRouteImport.update({
  id: '/api/v1/chat/history',
  path: '/api/v1/chat/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatMessagesRoute = ApiV1ChatMessagesRouteImport.update({
  id: '/api/v1/chat/messages',
  path: '/api/v1/chat/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatThreadsRoute = ApiV1ChatThreadsRouteImport.update({
  id: '/api/v1/chat/threads',
  path: '/api/v1/chat/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PushRegisterTokenRoute = ApiV1PushRegisterTokenRouteImport.update({
  id: '/api/v1/push/register-token',
  path: '/api/v1/push/register-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChatMessagesStreamRoute = ApiV1ChatMessagesStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiV1ChatMessagesRoute,
} as any)
const ApiV1ScreenersTypeResponsesRoute =
  ApiV1ScreenersTypeResponsesRouteImport.update({
    id: '/$type/responses',
    path: '/$type/responses',
    getParentRoute: () => ApiV1ScreenersRoute,
  } as any)
const ApiV1AdminUsersUserIdCostRoute =
  ApiV1AdminUsersUserIdCostRouteImport.update({
    id: '/api/v1/admin/users/$userId/cost',
    path: '/api/v1/admin/users/$userId/cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CallsSessionsIdEndRoute = ApiV1CallsSessionsIdEndRouteImport.update({
  id: '/$id/end',
  path: '/$id/end',
  getParentRoute: () => ApiV1CallsSessionsRoute,
} as any)
const ApiV1CallsSessionsIdTurnsRoute =
  ApiV1CallsSessionsIdTurnsRouteImport.update({
    id: '/$id/turns',
    path: '/$id/turns',
    getParentRoute: () => ApiV1CallsSessionsRoute,
  } as any)
const ApiV1ChatThreadsIdMessagesRoute =
  ApiV1ChatThreadsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiV1ChatThreadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crisis': typeof CrisisRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/care': typeof AuthenticatedCareRoute
  '/chat': typeof AuthenticatedChatRoute
  '/check-ins': typeof AuthenticatedCheckInsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/crisis': typeof AuthenticatedAdminCrisisRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/envcheck': typeof ApiPublicEnvcheckRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/v1/account': typeof ApiV1AccountRoute
  '/api/v1/crisis-resources': typeof ApiV1CrisisResourcesRoute
  '/api/v1/entitlements': typeof ApiV1EntitlementsRoute
  '/api/v1/exercises': typeof ApiV1ExercisesRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/habits': typeof ApiV1HabitsRoute
  '/api/v1/mood': typeof ApiV1MoodRoute
  '/api/v1/onboarding': typeof ApiV1OnboardingRoute
  '/api/v1/personas': typeof ApiV1PersonasRoute
  '/api/v1/preferences': typeof ApiV1PreferencesRoute
  '/api/v1/profile': typeof ApiV1ProfileRoute
  '/api/v1/screeners': typeof ApiV1ScreenersRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/evaluate-nudges': typeof ApiPublicHooksEvaluateNudgesRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/api/v1/billing/checkout': typeof ApiV1BillingCheckoutRoute
  '/api/v1/billing/portal': typeof ApiV1BillingPortalRoute
  '/api/v1/billing/verify-receipt': typeof ApiV1BillingVerifyReceiptRoute
  '/api/v1/calls/sessions': typeof ApiV1CallsSessionsRouteWithChildren
  '/api/v1/chat/history': typeof ApiV1ChatHistoryRoute
  '/api/v1/chat/messages': typeof ApiV1ChatMessagesRouteWithChildren
  '/api/v1/chat/threads': typeof ApiV1ChatThreadsRouteWithChildren
  '/api/v1/push/register-token': typeof ApiV1PushRegisterTokenRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/api/v1/chat/messages/stream': typeof ApiV1ChatMessagesStreamRoute
  '/api/v1/screeners/$type/responses': typeof ApiV1ScreenersTypeResponsesRoute
  '/api/v1/admin/users/$userId/cost': typeof ApiV1AdminUsersUserIdCostRoute
  '/api/v1/calls/sessions/$id/end': typeof ApiV1CallsSessionsIdEndRoute
  '/api/v1/calls/sessions/$id/turns': typeof ApiV1CallsSessionsIdTurnsRoute
  '/api/v1/chat/threads/$id/messages': typeof ApiV1ChatThreadsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crisis': typeof CrisisRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/care': typeof AuthenticatedCareRoute
  '/chat': typeof AuthenticatedChatRoute
  '/check-ins': typeof AuthenticatedCheckInsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/crisis': typeof AuthenticatedAdminCrisisRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/envcheck': typeof ApiPublicEnvcheckRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/v1/account': typeof ApiV1AccountRoute
  '/api/v1/crisis-resources': typeof ApiV1CrisisResourcesRoute
  '/api/v1/entitlements': typeof ApiV1EntitlementsRoute
  '/api/v1/exercises': typeof ApiV1ExercisesRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/habits': typeof ApiV1HabitsRoute
  '/api/v1/mood': typeof ApiV1MoodRoute
  '/api/v1/onboarding': typeof ApiV1OnboardingRoute
  '/api/v1/personas': typeof ApiV1PersonasRoute
  '/api/v1/preferences': typeof ApiV1PreferencesRoute
  '/api/v1/profile': typeof ApiV1ProfileRoute
  '/api/v1/screeners': typeof ApiV1ScreenersRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/evaluate-nudges': typeof ApiPublicHooksEvaluateNudgesRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/api/v1/billing/checkout': typeof ApiV1BillingCheckoutRoute
  '/api/v1/billing/portal': typeof ApiV1BillingPortalRoute
  '/api/v1/billing/verify-receipt': typeof ApiV1BillingVerifyReceiptRoute
  '/api/v1/calls/sessions': typeof ApiV1CallsSessionsRouteWithChildren
  '/api/v1/chat/history': typeof ApiV1ChatHistoryRoute
  '/api/v1/chat/messages': typeof ApiV1ChatMessagesRouteWithChildren
  '/api/v1/chat/threads': typeof ApiV1ChatThreadsRouteWithChildren
  '/api/v1/push/register-token': typeof ApiV1PushRegisterTokenRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/api/v1/chat/messages/stream': typeof ApiV1ChatMessagesStreamRoute
  '/api/v1/screeners/$type/responses': typeof ApiV1ScreenersTypeResponsesRoute
  '/api/v1/admin/users/$userId/cost': typeof ApiV1AdminUsersUserIdCostRoute
  '/api/v1/calls/sessions/$id/end': typeof ApiV1CallsSessionsIdEndRoute
  '/api/v1/calls/sessions/$id/turns': typeof ApiV1CallsSessionsIdTurnsRoute
  '/api/v1/chat/threads/$id/messages': typeof ApiV1ChatThreadsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/crisis': typeof CrisisRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/care': typeof AuthenticatedCareRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/check-ins': typeof AuthenticatedCheckInsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/crisis': typeof AuthenticatedAdminCrisisRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/envcheck': typeof ApiPublicEnvcheckRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/v1/account': typeof ApiV1AccountRoute
  '/api/v1/crisis-resources': typeof ApiV1CrisisResourcesRoute
  '/api/v1/entitlements': typeof ApiV1EntitlementsRoute
  '/api/v1/exercises': typeof ApiV1ExercisesRoute
  '/api/v1/export': typeof ApiV1ExportRoute
  '/api/v1/habits': typeof ApiV1HabitsRoute
  '/api/v1/mood': typeof ApiV1MoodRoute
  '/api/v1/onboarding': typeof ApiV1OnboardingRoute
  '/api/v1/personas': typeof ApiV1PersonasRoute
  '/api/v1/preferences': typeof ApiV1PreferencesRoute
  '/api/v1/profile': typeof ApiV1ProfileRoute
  '/api/v1/screeners': typeof ApiV1ScreenersRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/evaluate-nudges': typeof ApiPublicHooksEvaluateNudgesRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/api/v1/billing/checkout': typeof ApiV1BillingCheckoutRoute
  '/api/v1/billing/portal': typeof ApiV1BillingPortalRoute
  '/api/v1/billing/verify-receipt': typeof ApiV1BillingVerifyReceiptRoute
  '/api/v1/calls/sessions': typeof ApiV1CallsSessionsRouteWithChildren
  '/api/v1/chat/history': typeof ApiV1ChatHistoryRoute
  '/api/v1/chat/messages': typeof ApiV1ChatMessagesRouteWithChildren
  '/api/v1/chat/threads': typeof ApiV1ChatThreadsRouteWithChildren
  '/api/v1/push/register-token': typeof ApiV1PushRegisterTokenRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/api/v1/chat/messages/stream': typeof ApiV1ChatMessagesStreamRoute
  '/api/v1/screeners/$type/responses': typeof ApiV1ScreenersTypeResponsesRoute
  '/api/v1/admin/users/$userId/cost': typeof ApiV1AdminUsersUserIdCostRoute
  '/api/v1/calls/sessions/$id/end': typeof ApiV1CallsSessionsIdEndRoute
  '/api/v1/calls/sessions/$id/turns': typeof ApiV1CallsSessionsIdTurnsRoute
  '/api/v1/chat/threads/$id/messages': typeof ApiV1ChatThreadsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crisis'
    | '/legal'
    | '/reset-password'
    | '/admin'
    | '/care'
    | '/chat'
    | '/check-ins'
    | '/dashboard'
    | '/exercises'
    | '/habits'
    | '/insights'
    | '/onboarding'
    | '/plans'
    | '/settings'
    | '/support'
    | '/admin/audit'
    | '/admin/crisis'
    | '/admin/support'
    | '/admin/team'
    | '/api/public/envcheck'
    | '/api/public/unsubscribe'
    | '/api/v1/account'
    | '/api/v1/crisis-resources'
    | '/api/v1/entitlements'
    | '/api/v1/exercises'
    | '/api/v1/export'
    | '/api/v1/habits'
    | '/api/v1/mood'
    | '/api/v1/onboarding'
    | '/api/v1/personas'
    | '/api/v1/preferences'
    | '/api/v1/profile'
    | '/api/v1/screeners'
    | '/admin/'
    | '/admin/users/$userId'
    | '/api/public/hooks/evaluate-nudges'
    | '/api/public/hooks/stripe-webhook'
    | '/api/v1/billing/checkout'
    | '/api/v1/billing/portal'
    | '/api/v1/billing/verify-receipt'
    | '/api/v1/calls/sessions'
    | '/api/v1/chat/history'
    | '/api/v1/chat/messages'
    | '/api/v1/chat/threads'
    | '/api/v1/push/register-token'
    | '/admin/users/'
    | '/api/v1/chat/messages/stream'
    | '/api/v1/screeners/$type/responses'
    | '/api/v1/admin/users/$userId/cost'
    | '/api/v1/calls/sessions/$id/end'
    | '/api/v1/calls/sessions/$id/turns'
    | '/api/v1/chat/threads/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/crisis'
    | '/legal'
    | '/reset-password'
    | '/care'
    | '/chat'
    | '/check-ins'
    | '/dashboard'
    | '/exercises'
    | '/habits'
    | '/insights'
    | '/onboarding'
    | '/plans'
    | '/settings'
    | '/support'
    | '/admin/audit'
    | '/admin/crisis'
    | '/admin/support'
    | '/admin/team'
    | '/api/public/envcheck'
    | '/api/public/unsubscribe'
    | '/api/v1/account'
    | '/api/v1/crisis-resources'
    | '/api/v1/entitlements'
    | '/api/v1/exercises'
    | '/api/v1/export'
    | '/api/v1/habits'
    | '/api/v1/mood'
    | '/api/v1/onboarding'
    | '/api/v1/personas'
    | '/api/v1/preferences'
    | '/api/v1/profile'
    | '/api/v1/screeners'
    | '/admin'
    | '/admin/users/$userId'
    | '/api/public/hooks/evaluate-nudges'
    | '/api/public/hooks/stripe-webhook'
    | '/api/v1/billing/checkout'
    | '/api/v1/billing/portal'
    | '/api/v1/billing/verify-receipt'
    | '/api/v1/calls/sessions'
    | '/api/v1/chat/history'
    | '/api/v1/chat/messages'
    | '/api/v1/chat/threads'
    | '/api/v1/push/register-token'
    | '/admin/users'
    | '/api/v1/chat/messages/stream'
    | '/api/v1/screeners/$type/responses'
    | '/api/v1/admin/users/$userId/cost'
    | '/api/v1/calls/sessions/$id/end'
    | '/api/v1/calls/sessions/$id/turns'
    | '/api/v1/chat/threads/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/crisis'
    | '/legal'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/care'
    | '/_authenticated/chat'
    | '/_authenticated/check-ins'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercises'
    | '/_authenticated/habits'
    | '/_authenticated/insights'
    | '/_authenticated/onboarding'
    | '/_authenticated/plans'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/crisis'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/team'
    | '/api/public/envcheck'
    | '/api/public/unsubscribe'
    | '/api/v1/account'
    | '/api/v1/crisis-resources'
    | '/api/v1/entitlements'
    | '/api/v1/exercises'
    | '/api/v1/export'
    | '/api/v1/habits'
    | '/api/v1/mood'
    | '/api/v1/onboarding'
    | '/api/v1/personas'
    | '/api/v1/preferences'
    | '/api/v1/profile'
    | '/api/v1/screeners'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/hooks/evaluate-nudges'
    | '/api/public/hooks/stripe-webhook'
    | '/api/v1/billing/checkout'
    | '/api/v1/billing/portal'
    | '/api/v1/billing/verify-receipt'
    | '/api/v1/calls/sessions'
    | '/api/v1/chat/history'
    | '/api/v1/chat/messages'
    | '/api/v1/chat/threads'
    | '/api/v1/push/register-token'
    | '/_authenticated/admin/users/'
    | '/api/v1/chat/messages/stream'
    | '/api/v1/screeners/$type/responses'
    | '/api/v1/admin/users/$userId/cost'
    | '/api/v1/calls/sessions/$id/end'
    | '/api/v1/calls/sessions/$id/turns'
    | '/api/v1/chat/threads/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CrisisRoute: typeof CrisisRoute
  LegalRoute: typeof LegalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicEnvcheckRoute: typeof ApiPublicEnvcheckRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiV1AccountRoute: typeof ApiV1AccountRoute
  ApiV1CrisisResourcesRoute: typeof ApiV1CrisisResourcesRoute
  ApiV1EntitlementsRoute: typeof ApiV1EntitlementsRoute
  ApiV1ExercisesRoute: typeof ApiV1ExercisesRoute
  ApiV1ExportRoute: typeof ApiV1ExportRoute
  ApiV1HabitsRoute: typeof ApiV1HabitsRoute
  ApiV1MoodRoute: typeof ApiV1MoodRoute
  ApiV1OnboardingRoute: typeof ApiV1OnboardingRoute
  ApiV1PersonasRoute: typeof ApiV1PersonasRoute
  ApiV1PreferencesRoute: typeof ApiV1PreferencesRoute
  ApiV1ProfileRoute: typeof ApiV1ProfileRoute
  ApiV1ScreenersRoute: typeof ApiV1ScreenersRouteWithChildren
  ApiPublicHooksEvaluateNudgesRoute: typeof ApiPublicHooksEvaluateNudgesRoute
  ApiPublicHooksStripeWebhookRoute: typeof ApiPublicHooksStripeWebhookRoute
  ApiV1BillingCheckoutRoute: typeof ApiV1BillingCheckoutRoute
  ApiV1BillingPortalRoute: typeof ApiV1BillingPortalRoute
  ApiV1BillingVerifyReceiptRoute: typeof ApiV1BillingVerifyReceiptRoute
  ApiV1CallsSessionsRoute: typeof ApiV1CallsSessionsRouteWithChildren
  ApiV1ChatHistoryRoute: typeof ApiV1ChatHistoryRoute
  ApiV1ChatMessagesRoute: typeof ApiV1ChatMessagesRouteWithChildren
  ApiV1ChatThreadsRoute: typeof ApiV1ChatThreadsRouteWithChildren
  ApiV1PushRegisterTokenRoute: typeof ApiV1PushRegisterTokenRoute
  ApiV1AdminUsersUserIdCostRoute: typeof ApiV1AdminUsersUserIdCostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care': {
      id: '/_authenticated/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AuthenticatedCareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-ins': {
      id: '/_authenticated/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof AuthenticatedCheckInsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/crisis': {
      id: '/_authenticated/admin/crisis'
      path: '/crisis'
      fullPath: '/admin/crisis'
      preLoaderRoute: typeof AuthenticatedAdminCrisisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/envcheck': {
      id: '/api/public/envcheck'
      path: '/api/public/envcheck'
      fullPath: '/api/public/envcheck'
      preLoaderRoute: typeof ApiPublicEnvcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/account': {
      id: '/api/v1/account'
      path: '/api/v1/account'
      fullPath: '/api/v1/account'
      preLoaderRoute: typeof ApiV1AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/crisis-resources': {
      id: '/api/v1/crisis-resources'
      path: '/api/v1/crisis-resources'
      fullPath: '/api/v1/crisis-resources'
      preLoaderRoute: typeof ApiV1CrisisResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entitlements': {
      id: '/api/v1/entitlements'
      path: '/api/v1/entitlements'
      fullPath: '/api/v1/entitlements'
      preLoaderRoute: typeof ApiV1EntitlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exercises': {
      id: '/api/v1/exercises'
      path: '/api/v1/exercises'
      fullPath: '/api/v1/exercises'
      preLoaderRoute: typeof ApiV1ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export': {
      id: '/api/v1/export'
      path: '/api/v1/export'
      fullPath: '/api/v1/export'
      preLoaderRoute: typeof ApiV1ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/habits': {
      id: '/api/v1/habits'
      path: '/api/v1/habits'
      fullPath: '/api/v1/habits'
      preLoaderRoute: typeof ApiV1HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mood': {
      id: '/api/v1/mood'
      path: '/api/v1/mood'
      fullPath: '/api/v1/mood'
      preLoaderRoute: typeof ApiV1MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/onboarding': {
      id: '/api/v1/onboarding'
      path: '/api/v1/onboarding'
      fullPath: '/api/v1/onboarding'
      preLoaderRoute: typeof ApiV1OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/personas': {
      id: '/api/v1/personas'
      path: '/api/v1/personas'
      fullPath: '/api/v1/personas'
      preLoaderRoute: typeof ApiV1PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/preferences': {
      id: '/api/v1/preferences'
      path: '/api/v1/preferences'
      fullPath: '/api/v1/preferences'
      preLoaderRoute: typeof ApiV1PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile': {
      id: '/api/v1/profile'
      path: '/api/v1/profile'
      fullPath: '/api/v1/profile'
      preLoaderRoute: typeof ApiV1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/screeners': {
      id: '/api/v1/screeners'
      path: '/api/v1/screeners'
      fullPath: '/api/v1/screeners'
      preLoaderRoute: typeof ApiV1ScreenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/evaluate-nudges': {
      id: '/api/public/hooks/evaluate-nudges'
      path: '/api/public/hooks/evaluate-nudges'
      fullPath: '/api/public/hooks/evaluate-nudges'
      preLoaderRoute: typeof ApiPublicHooksEvaluateNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe-webhook': {
      id: '/api/public/hooks/stripe-webhook'
      path: '/api/public/hooks/stripe-webhook'
      fullPath: '/api/public/hooks/stripe-webhook'
      preLoaderRoute: typeof ApiPublicHooksStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/checkout': {
      id: '/api/v1/billing/checkout'
      path: '/api/v1/billing/checkout'
      fullPath: '/api/v1/billing/checkout'
      preLoaderRoute: typeof ApiV1BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/portal': {
      id: '/api/v1/billing/portal'
      path: '/api/v1/billing/portal'
      fullPath: '/api/v1/billing/portal'
      preLoaderRoute: typeof ApiV1BillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/verify-receipt': {
      id: '/api/v1/billing/verify-receipt'
      path: '/api/v1/billing/verify-receipt'
      fullPath: '/api/v1/billing/verify-receipt'
      preLoaderRoute: typeof ApiV1BillingVerifyReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calls/sessions': {
      id: '/api/v1/calls/sessions'
      path: '/api/v1/calls/sessions'
      fullPath: '/api/v1/calls/sessions'
      preLoaderRoute: typeof ApiV1CallsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/history': {
      id: '/api/v1/chat/history'
      path: '/api/v1/chat/history'
      fullPath: '/api/v1/chat/history'
      preLoaderRoute: typeof ApiV1ChatHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/messages': {
      id: '/api/v1/chat/messages'
      path: '/api/v1/chat/messages'
      fullPath: '/api/v1/chat/messages'
      preLoaderRoute: typeof ApiV1ChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/threads': {
      id: '/api/v1/chat/threads'
      path: '/api/v1/chat/threads'
      fullPath: '/api/v1/chat/threads'
      preLoaderRoute: typeof ApiV1ChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/push/register-token': {
      id: '/api/v1/push/register-token'
      path: '/api/v1/push/register-token'
      fullPath: '/api/v1/push/register-token'
      preLoaderRoute: typeof ApiV1PushRegisterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/messages/stream': {
      id: '/api/v1/chat/messages/stream'
      path: '/stream'
      fullPath: '/api/v1/chat/messages/stream'
      preLoaderRoute: typeof ApiV1ChatMessagesStreamRouteImport
      parentRoute: typeof ApiV1ChatMessagesRoute
    }
    '/api/v1/screeners/$type/responses': {
      id: '/api/v1/screeners/$type/responses'
      path: '/$type/responses'
      fullPath: '/api/v1/screeners/$type/responses'
      preLoaderRoute: typeof ApiV1ScreenersTypeResponsesRouteImport
      parentRoute: typeof ApiV1ScreenersRoute
    }
    '/api/v1/admin/users/$userId/cost': {
      id: '/api/v1/admin/users/$userId/cost'
      path: '/api/v1/admin/users/$userId/cost'
      fullPath: '/api/v1/admin/users/$userId/cost'
      preLoaderRoute: typeof ApiV1AdminUsersUserIdCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calls/sessions/$id/end': {
      id: '/api/v1/calls/sessions/$id/end'
      path: '/$id/end'
      fullPath: '/api/v1/calls/sessions/$id/end'
      preLoaderRoute: typeof ApiV1CallsSessionsIdEndRouteImport
      parentRoute: typeof ApiV1CallsSessionsRoute
    }
    '/api/v1/calls/sessions/$id/turns': {
      id: '/api/v1/calls/sessions/$id/turns'
      path: '/$id/turns'
      fullPath: '/api/v1/calls/sessions/$id/turns'
      preLoaderRoute: typeof ApiV1CallsSessionsIdTurnsRouteImport
      parentRoute: typeof ApiV1CallsSessionsRoute
    }
    '/api/v1/chat/threads/$id/messages': {
      id: '/api/v1/chat/threads/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/v1/chat/threads/$id/messages'
      preLoaderRoute: typeof ApiV1ChatThreadsIdMessagesRouteImport
      parentRoute: typeof ApiV1ChatThreadsRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCrisisRoute: typeof AuthenticatedAdminCrisisRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminCrisisRoute: AuthenticatedAdminCrisisRoute,
    AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCareRoute: typeof AuthenticatedCareRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCheckInsRoute: typeof AuthenticatedCheckInsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCareRoute: AuthenticatedCareRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCheckInsRoute: AuthenticatedCheckInsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiV1ScreenersRouteChildren {
  ApiV1ScreenersTypeResponsesRoute: typeof ApiV1ScreenersTypeResponsesRoute
}

const ApiV1ScreenersRouteChildren: ApiV1ScreenersRouteChildren = {
  ApiV1ScreenersTypeResponsesRoute: ApiV1ScreenersTypeResponsesRoute,
}

const ApiV1ScreenersRouteWithChildren = ApiV1ScreenersRoute._addFileChildren(
  ApiV1ScreenersRouteChildren,
)

interface ApiV1CallsSessionsRouteChildren {
  ApiV1CallsSessionsIdEndRoute: typeof ApiV1CallsSessionsIdEndRoute
  ApiV1CallsSessionsIdTurnsRoute: typeof ApiV1CallsSessionsIdTurnsRoute
}

const ApiV1CallsSessionsRouteChildren: ApiV1CallsSessionsRouteChildren = {
  ApiV1CallsSessionsIdEndRoute: ApiV1CallsSessionsIdEndRoute,
  ApiV1CallsSessionsIdTurnsRoute: ApiV1CallsSessionsIdTurnsRoute,
}

const ApiV1CallsSessionsRouteWithChildren =
  ApiV1CallsSessionsRoute._addFileChildren(ApiV1CallsSessionsRouteChildren)

interface ApiV1ChatMessagesRouteChildren {
  ApiV1ChatMessagesStreamRoute: typeof ApiV1ChatMessagesStreamRoute
}

const ApiV1ChatMessagesRouteChildren: ApiV1ChatMessagesRouteChildren = {
  ApiV1ChatMessagesStreamRoute: ApiV1ChatMessagesStreamRoute,
}

const ApiV1ChatMessagesRouteWithChildren =
  ApiV1ChatMessagesRoute._addFileChildren(ApiV1ChatMessagesRouteChildren)

interface ApiV1ChatThreadsRouteChildren {
  ApiV1ChatThreadsIdMessagesRoute: typeof ApiV1ChatThreadsIdMessagesRoute
}

const ApiV1ChatThreadsRouteChildren: ApiV1ChatThreadsRouteChildren = {
  ApiV1ChatThreadsIdMessagesRoute: ApiV1ChatThreadsIdMessagesRoute,
}

const ApiV1ChatThreadsRouteWithChildren =
  ApiV1ChatThreadsRoute._addFileChildren(ApiV1ChatThreadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CrisisRoute: CrisisRoute,
  LegalRoute: LegalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicEnvcheckRoute: ApiPublicEnvcheckRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiV1AccountRoute: ApiV1AccountRoute,
  ApiV1CrisisResourcesRoute: ApiV1CrisisResourcesRoute,
  ApiV1EntitlementsRoute: ApiV1EntitlementsRoute,
  ApiV1ExercisesRoute: ApiV1ExercisesRoute,
  ApiV1ExportRoute: ApiV1ExportRoute,
  ApiV1HabitsRoute: ApiV1HabitsRoute,
  ApiV1MoodRoute: ApiV1MoodRoute,
  ApiV1OnboardingRoute: ApiV1OnboardingRoute,
  ApiV1PersonasRoute: ApiV1PersonasRoute,
  ApiV1PreferencesRoute: ApiV1PreferencesRoute,
  ApiV1ProfileRoute: ApiV1ProfileRoute,
  ApiV1ScreenersRoute: ApiV1ScreenersRouteWithChildren,
  ApiPublicHooksEvaluateNudgesRoute: ApiPublicHooksEvaluateNudgesRoute,
  ApiPublicHooksStripeWebhookRoute: ApiPublicHooksStripeWebhookRoute,
  ApiV1BillingCheckoutRoute: ApiV1BillingCheckoutRoute,
  ApiV1BillingPortalRoute: ApiV1BillingPortalRoute,
  ApiV1BillingVerifyReceiptRoute: ApiV1BillingVerifyReceiptRoute,
  ApiV1CallsSessionsRoute: ApiV1CallsSessionsRouteWithChildren,
  ApiV1ChatHistoryRoute: ApiV1ChatHistoryRoute,
  ApiV1ChatMessagesRoute: ApiV1ChatMessagesRouteWithChildren,
  ApiV1ChatThreadsRoute: ApiV1ChatThreadsRouteWithChildren,
  ApiV1PushRegisterTokenRoute: ApiV1PushRegisterTokenRoute,
  ApiV1AdminUsersUserIdCostRoute: ApiV1AdminUsersUserIdCostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
